### ISSUE TITLE
Create helper functions for RegressionPlot plot fit functions

### ISSUE THREAD

**Issue by MatthewSpofford** [MatthewSpofford/Multiscale-Statistical-Analysis#26]

**Comment by MatthewSpofford** [comment]
```
ERROR:root:Traceback (most recent call last):
  File "C:\workspace\MultiscaleStatisticalAnalysis\CanvasPanel.py", line 796, in quadratic_fit_plot
    popt, pcov = self.get_cvf().quad_data(np.array(self.get_xr()), np.array(y_values))
  File "C:\workspace\MultiscaleStatisticalAnalysis\CurveFit.py", line 27, in quad_data
    def quad_data(self, x, y): return curve_fit(self.quad_fit, x, y, maxfev=self.get_maxfev())
  File "C:\workspace\MultiscaleStatisticalAnalysis\multiscale-stat-env\lib\site-packages\scipy\optimize\minpack.py", line 828, in curve_fit
    warnings.warn('Covariance of the parameters could not be estimated',
scipy.optimize.optimize.OptimizeWarning: Covariance of the parameters could not be estimated
```
