### ISSUE TITLE
Changes from workbook making feature prevent statistical analysis from operating

### ISSUE THREAD

**Issue by MatthewSpofford** [MatthewSpofford/Multiscale-Statistical-Analysis#27]
Originated after new workbook fixes (#9).

```
C:\workspace\MultiscaleStatisticalAnalysis\StatsTestsUI.py:282: RuntimeWarning: divide by zero encountered in double_scalars
  f_val = np.round_(var[0] / var[1], 4)
Traceback (most recent call last):
  File "C:\workspace\MultiscaleStatisticalAnalysis\StatsTestsUI.py", line 134, in OnOK
    self.get_flist(), self.get_tree_menu(), self.get_root(), 'F-Value by Scale',
  File "C:\workspace\MultiscaleStatisticalAnalysis\StatsTestsUI.py", line 561, in get_root
    def get_root(self): return self.rootself.root
AttributeError: 'FtestDialog' object has no attribute 'rootself'
```

**Comment by MatthewSpofford** [comment]
Could be possible that this is recurring from the previous divide by zero issues (#17).

**Comment by MatthewSpofford** [comment]
> 
> 
> Could be possible that this is recurring from the previous divide by zero issues (#17).

This appears to identical. Although there is a new issue that was unnoticed, since the rootself attribute is not found.
