### ISSUE TITLE
Changes from workbook causing `rootself` attribute to not be found

### ISSUE THREAD

**Issue by MatthewSpofford** [MatthewSpofford/Multiscale-Statistical-Analysis#30]
Originated after new workbook fixes (#9).

```
Traceback (most recent call last):
  File "C:\workspace\MultiscaleStatisticalAnalysis\StatsTestsUI.py", line 134, in OnOK
    self.get_flist(), self.get_tree_menu(), self.get_root(), 'F-Value by Scale',
  File "C:\workspace\MultiscaleStatisticalAnalysis\StatsTestsUI.py", line 561, in get_root
    def get_root(self): return self.rootself.root
AttributeError: 'FtestDialog' object has no attribute 'rootself'
```

**Comment by MatthewSpofford** [comment]
Found to be a typo
