### ISSUE TITLE
Curve fit errors: 'PlotData' object has no attribute 'get_data', cubic_fit() argument after * must be an iterable, not int

### ISSUE THREAD

**Issue by MatthewSpofford** [MatthewSpofford/Multiscale-Statistical-Analysis#32]
Errors appeared in the error/warning window. Removing try/exceptions wrapped around these functions give more detailed results.

Explanation of `*` operator in function call: https://stackoverflow.com/questions/2921847/what-does-the-star-operator-mean-in-a-function-call.

- [x] get_data attribute error
- [x] plot fit error using `*` use `poptbest` iterable in fit functions

**Comment by MatthewSpofford** [comment]
Regarding cubic_fit() argument after * must be an iterable, not int
```
Traceback (most recent call last):
  File "C:\workspace\MultiscaleStatisticalAnalysis\main.py", line 82, in OnRegression
    gdlg4.get_graph().cubic_fit_plot()
  File "C:\workspace\MultiscaleStatisticalAnalysis\CanvasPanel.py", line 963, in cubic_fit_plot
    self.set_curve(self.get_cvf().cubic_fit(np.array(self.get_x_plot()), *poptbest))
TypeError: cubic_fit() argument after * must be an iterable, not int
```
This issue also appears to occurring with other fit functions and should be equally resolved.

**Comment by MatthewSpofford** [comment]
For resolving `get_data()` attribute error: `self.workbook = self.tree_menu.GetItemData(swb)` in `CanvasPanel` changed to `self.workbook = self.tree_menu.GetItemData(swb).get_wb()`.

The various instances of `self.get_tree_menu().SetItemData(self.get_swb(), self.get_wb())` also had to be removed, as it was replacing the `PlotData` with the `Workbook` already contained in the `PlotData`.

**Comment by MatthewSpofford** [comment]
> 
> 
> Regarding cubic_fit() argument after * must be an iterable, not int
> 
> ```
> Traceback (most recent call last):
>   File "C:\workspace\MultiscaleStatisticalAnalysis\main.py", line 82, in OnRegression
>     gdlg4.get_graph().cubic_fit_plot()
>   File "C:\workspace\MultiscaleStatisticalAnalysis\CanvasPanel.py", line 963, in cubic_fit_plot
>     self.set_curve(self.get_cvf().cubic_fit(np.array(self.get_x_plot()), *poptbest))
> TypeError: cubic_fit() argument after * must be an iterable, not int
> ```
> 
> This issue also appears to occurring with other fit functions and should be equally resolved.

Appears to be because the poptbest is not an iterable, and is just a single variable. Seems like an easy fix.

**Comment by MatthewSpofford** [comment]
> Appears to be because the poptbest is not an iterable, and is just a single variable. Seems like an easy fix.

Not exactly sure how the math works in order to fix this.

**Comment by MatthewSpofford** [comment]
As stated in 928da9b, this only occured because scipy could not find the correct fit. Hopefully this is not a mathematical issue, and is meant to occur. This issue is closed until further notice.
